name: recordatorio_pastilla
description: "App de recordatorio de medicamentos para Luis"
# La version debe ser superior a la anterior si vas a subirla
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Notificaciones para las alarmas
  awesome_notifications: ^0.8.2
  
  # Base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Iconos adicionales
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter para mantener el código limpio
  flutter_lints: ^3.0.0
  
  # Generador de base de datos
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Si tienes imágenes o fuentes, se declaran aquí abajo
  # assets:
  #   - assets/images/