name: Build iOS
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
            
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

- name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Esta versión es moderna y estable
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean and Pod Update
        run: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod repo update
          pod install

      - name: Build iOS (No Sign)
        run: flutter build ios --release --no-codesign --no-bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos