name: Build iOS
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # No ponemos version fija, dejamos que traiga la ultima estable
          # Esto forzara a que supere la 3.11.5 que te pide el error
          cache: true

      - name: Install Dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Install Pods
        run: |
          cd ios
          pod install || true

      - name: Build iOS (No Sign)
        run: flutter build ios --release --no-codesign --no-bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos