name: Build iOS
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # Actualizado a v4
            
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install Pods
        run: cd ios && pod install || true # Para que no se trabe si no hay pods aún

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Actualizado a v4 para arreglar el error
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app